language: rust
rust:
- stable
before_install:
- sudo apt update
- sudo apt install -y libudev-dev
stages:
- name: build
  if: tag !~ ^v
- name: publish-github
  if: tag =~ ^v
- name: publish-crate
  if: tag =~ ^v
jobs:
  include:
  - stage: build
    script: cargo build
  - stage: publish-crate
    script: cargo package && cargo login "$CRATES_TOKEN" && cargo publish
  - stage: publish-github
    script: cargo build --release
    deploy:
      provider: releases
      api_key: "$GITHUB_API_KEY"
      file: target/release/razer-naga-2014-key-remap
      skip_cleanup: true
      on:
        tags: true

