# Valid key values are:
# Esc, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
# Grave, _1, _2, _3, _4, _5, _6, _7, _8, _9, _0, Minus, _Equal, BackSpace,
# Tab, Q, W, E, R, T, Y, U, I, O, P, LeftBrace, RightBrace, BackSlash,
# CapsLock, A, S, D, F, G, H, J, K, L, SemiColon, Apostrophe, Enter
# LeftShift, Z, X, C, V, B, N, M, Comma, Dot, Slash, RightShift
# LeftControl, LeftMeta, LeftAlt, Space, RightAlt, RightMeta, RightControl
#
# SysRq, ScrollLock,
# Insert, Home, PageUp
# Delete, End, PageDown
#
# Up,
# Left, Down, Right
#
# NumLock, LineFeed, ScrollUp, ScrollDown,
# F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24

[keys]
1 = 'F1'
2 = 'F2'
3 = 'F3'
4 = 'F4'
5 = 'F5'
6 = 'F6'
7 = 'F7'
8 = 'F8'
9 = 'F9'
10 = 'F10'
11 = 'F11'
12 = 'F12'
